### ISSUE TITLE
Lazy doesn't impl Debug

### ISSUE THREAD

**Issue by swolchok** [khuey/lazy-init#7]
This prevents any type that contains a Lazy from deriving Debug, which is inconvenient.

**Comment by khuey** [comment]
Indeed. I skipped this before because it's not obvious what to do for `LazyTransform` (either you can't print the "before" type in the Debug impl, or you have to lock and complicate the state machine somehow). `Lazy` doesn't have a meaningful "before" type though so it would be straightforward to implement Debug for it.
